### ISSUE TITLE
default values don't get saved properly

### ISSUE THREAD

**Issue by neojin** [amco/dolly#26]
Please see https://github.com/amco/ab/pull/693

I believe this is due to the differences between the `property` method and what is stored in `doc`

Steps to reproduce:

1. Create a dolly document with the following: `property :foo, class_name: Hash, default: {}`

2. in couch directly save an instance of this document, and make sure `foo` is not included (i.e `foo` should not be a key anywhere in the document)

3. load the document via `find`. set `document.foo = { 'bar' => 'baz' }` and `save`.

4. In couch, the data will be `foo: null` and NOT `foo: { 'bar' : 'baz' }`

**Comment by seancookr** [comment]
I believe this was closed by https://github.com/amco/dolly/pull/52 and I mislabeled the issue that was supposed to close.  closing this
