### ISSUE TITLE
Default Should Populate Attribute Before Save (maybe?)

### ISSUE THREAD

**Issue by Petercopter** [amco/dolly#38]
Given this line:
`property :created_at, class_name: Time, default: Time.now`

It appears that `default` is only run at the time the attribute is read.

It would be really cool if `default` actually populated the attribut before save, then it could be used for timestamps and all kinds of other fun defaulty type stuff.

**Comment by seancookr** [comment]
closing this as this test https://github.com/amco/dolly/blob/master/test/document_test.rb#L357 shows that defaults are populated before save
