### ISSUE TITLE
Authentication errors to database not properly caught by Exceptions

### ISSUE THREAD

**Issue by brlanier** [amco/dolly#58]
Update the error handling to provide info when your connection to couch is blocked for auth reasons.

**Comment by norcal82** [comment]
@javierg can I take this one for skunks?

**Comment by brlanier** [comment]
Actually, I think this one is mostly done in #60 unless there is a need to break down the error codes more

**Comment by seancookr** [comment]
This is solved by https://github.com/amco/dolly/pull/74, I am going to close this
