### ISSUE TITLE
Add `Valid?` blank method, to be implemented by inherited Document class.

### ISSUE THREAD

**Issue by javierg** [amco/dolly#70]
`save!` should check if object responds to `valid?` and raises an exception if invalid.

**Comment by seancookr** [comment]
Also a feature not for `1.0` stable IMO

**Comment by seancookr** [comment]
actually, in retrospect, I think this could be implemented in 1.0 stable.

**Comment by seancookr** [comment]
@javierg @rubenrails @netlogics This was finished in #76. I am closing the issue.

**Comment by rubenrails** [comment]
@seancookr How is #76 related to this issue? Am I missing something?

**Comment by seancookr** [comment]
@rubenrails sorry that was a typo. this was solved in #79
