### ISSUE TITLE
View generator and/or migration-based generation

### ISSUE THREAD

**Issue by smathy** [amco/dolly#8]
One thing I was thinking is that you could actually have just a single view for all the ID-based lookups, as long as you stick to that "type/id" format for the `_id`s.

```coffeescript
(d) ->
  if ti = d._id.split "/"
    emit ti
```

And then your view queries need to include that composite key, eg.

    /foo/_design/dolly/_view/id?key=["User", "foo@bar.com"]

**Comment by javierg** [comment]
After discussion this is no longer required
