### ISSUE TITLE
Add Enumberable Methods To Dolly::Collection

### ISSUE THREAD

**Issue by netlogics** [amco/dolly#87]
WIP
Open discussion for adding enumerable methods to Dolly::Colection.

**Comment by seancookr** [comment]
@netlogics I like this idea a lot.  it would allow us to not have to call `to_a` on everything when we want some simple enumerators.  :+1: 

I conceivably think this should be in `1.0` RC, but it may have to be delayed to `1.1` as `1.0` is now finally stable. in retrospect perhaps the attachments should have been for `1.1`

**Comment by netlogics** [comment]
Cool. 
1.1 seems like a good target.
